media: 
  input: src/assets/img
  output: ../assets/img
content:
  - name: posts
    label: Blog Posts
    path: src/posts
    type: collection
    view:
      fields: [ title, draft, date, description ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - { name: draft, label: Draft, default: true, type: boolean }
      - { name: description, label: Description, type: string }
      - { name: author, label: Author, default: Will Rynearson, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: pages
    label: Project Pages
    path: src/pages
    type: collection
    view:
      fields: [ title, draft, date, end-date, url, description, type, client, role ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: draft, label: Draft, default: true, type: boolean }
      - { name: date, label: Start Date, type: date }
      - { name: end-date, label: End Date, type: date }
      - { name: url, label: URL, type: string }
      - { name: description, label: Description, type: string }
      - { name: problem, label: Problem, type: string }
      - { name: outcome, label: Outcome, type: string }
      - name: type 
        label: Project Type
        type: select
        options:
          multiple: true
          creatable: true
          values:
          - value: personal
            label: Personal
          - value: professional
            label: Professional
          - value: academic
            label: Academic
      - { name: client, label: Project Client, type: string }
      - { name: role, label: My Role, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: recently
    label: Recently Posts
    path: src/recently
    type: collection
    view:
      fields: [ date, draft ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Start Date, type: date }
      - { name: draft, label: Draft, default: true, type: boolean }
      - { name: description, label: Description, type: string, default: Recently }
      - { name: body, label: Body, type: rich-text }
  - name: presentations
    label: Presentations
    path: src/presentations
    type: collection
    view:
      fields: [ title, date, draft ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, label: Layout, type: string, default: "layouts/reveal-layout.liquid" }
      - { name: date, label: Start Date, type: date }
      - { name: draft, label: Draft, default: true, type: boolean }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: text }