# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-59799094-3'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Projects', path: 'menu', url: 'projects.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'camera', link: 'https://wrynearson.github.io/portfolio/'}
- {icon: 'instagram', link: 'https://www.instagram.com/willrynearson/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/willrynearson/'}
- {icon: 'github', link: 'https://github.com/wrynearson/'}
- {icon: 'address-card', link: 'https://wrynearson.github.io/online-cv/'}


# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

# sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: ''
